# Generated by Django 4.1.7 on 2023-05-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerSite", "0002_image_remove_laptop_image_laptop_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="images",
        ),
        migrations.AddField(
            model_name="image",
            name="laptop",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="CustomerSite.laptop",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
