# Generated by Django 4.1.7 on 2023-04-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerSite", "0002_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="battery_life",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="laptop",
            name="display_size",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="laptop",
            name="gpu",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="laptop",
            name="processor",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="laptop",
            name="ram",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="laptop",
            name="storage",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="laptop",
            name="weight",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
