# Generated by Django 4.1.7 on 2023-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CustomerSite",
            "0003_laptop_battery_life_laptop_display_size_laptop_gpu_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pay",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="laptop",
            name="image",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("O", "Order"), ("D", "Delivery"), ("C", "Complete")],
                max_length=1,
            ),
        ),
    ]
