# Generated by Django 4.1.7 on 2023-05-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerSite", "0003_remove_laptop_images_image_laptop_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
