# Generated by Django 4.1.7 on 2023-05-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerSite", "0004_laptop_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="vourch",
        ),
    ]
