# Generated by Django 4.1.7 on 2023-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CustomerSite",
            "0004_order_pay_alter_laptop_image_alter_laptop_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pay",
            field=models.BooleanField(default=False),
        ),
    ]
