# Generated by Django 4.1.7 on 2023-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerSite", "0005_alter_order_pay"),
    ]

    operations = [
        migrations.RenameField(
            model_name="laptop",
            old_name="gpu",
            new_name="VGA",
        ),
        migrations.RenameField(
            model_name="laptop",
            old_name="storage",
            new_name="hard_disk",
        ),
        migrations.AddField(
            model_name="laptop",
            name="warranty",
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name="laptop",
            name="wireless",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
