# Generated by Django 4.1.7 on 2023-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerSite", "0006_rename_gpu_laptop_vga_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
