# Generated by Django 4.1.7 on 2023-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerSite", "0007_laptop_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
