# Generated by Django 4.1.7 on 2023-04-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerSite", "0008_alter_laptop_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="VGA",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="battery_life",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="display_size",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="hard_disk",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="processor",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="ram",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="weight",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="wireless",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
